### ISSUE TITLE
mastodon is a problem

### ISSUE THREAD

**Issue by bruceleerabbit** [skiant/get-in-touch#1]
My gnu social pod cannot remote follow https://witches.town/users/Skiant/ because it's on mastodon.  You need a non-mastodon account.

Also, the gnu social account you name in your list is old.

**Comment by vegaelle** [comment]
What about **not** telling people what they need and what they should use, especially when it’s free software vs another, compatible, free software?

Mastodon isn’t a problem. Your displaced behaviour is.

**Comment by skiant** [comment]
Being on Mastodon is a conscious choice that I made, just like protecting my account. 
Please do not consider you are entitled to anyone's social media updates ever again.
